name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to MavenCentral
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare env
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"

      - name: Build SDK
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: ./gradlew kumulos:assemble

      - name: Build sources
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: ./gradlew kumulos:androidSourcesJar

      - name: Publish to MavenCentral
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --max-workers 1 closeAndReleaseRepository
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
